name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Adjust or remove the environment as necessary

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud
        run: |
          # Example: Deploying a Cloud Run service
          gcloud run deploy your-service-name --image gcr.io/your-project-id/your-image-name --region your-region
          # Adjust the above command based on your specific deployment needs
