name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0 # Specify the Terraform version you are using

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="google_credentials=${{ secrets.GCP_SA_KEY }}" -var="project=your-gcp-project-id" -var="region=your-gcp-region"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
