name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Adjust to your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust for your project

      - name: Run tests
        run: echo "Add your test command here"
